<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/08/02 19:07:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=qdpm;host=127.0.0.1;port=3306',
  'profiler' => false,
  'username' => 'ostechnix',
  'password' => 'Password123%23%40%21',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
