<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/08/05 01:47:57
sfConfig::add(array(
  'mod_accessforbidden_enabled' => true,
  'mod_accessforbidden_view_class' => 'sfPHP',
));
