<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/08/03 05:44:21
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
