<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/08/03 01:50:46
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
