<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/08/03 01:51:47
sfConfig::add(array(
  'mod_versionsstatus_enabled' => true,
  'mod_versionsstatus_view_class' => 'sfPHP',
));
